package fr.osallek.osamodeditor.controller;

public enum ErrorCode {
    DEFAULT_ERROR,
    MISSING_PARAMETER,
    AREA_NOT_FOUND,
    TRADE_COMPANY_NOT_FOUND,
    CLIMATE_NOT_FOUND,
    COLONIAL_REGION_NOT_FOUND,
    COUNTRY_NOT_FOUND,
    CULTURE_NOT_FOUND,
    MONSOON_NOT_FOUND,
    PROVINCE_NOT_FOUND,
    RELIGION_NOT_FOUND,
    TERRAIN_NOT_FOUND,
    TRADE_GOOD_NOT_FOUND,
    TRADE_NODE_NOT_FOUND,
    WINTER_NOT_FOUND,
    INVALID_PARAMETER
}
